### ISSUE TITLE
website is not responsive

### ISSUE THREAD

**Issue by gkm0001** [PecanProject/web#31]
<img width="379" alt="Screenshot 2023-09-28 164534" src="https://github.com/PecanProject/web/assets/121250607/1466990a-2997-4ed9-a872-23af456b0f83">

As you can see website it not responsive. Kindle assign me this issue , I will fix it.

**Comment by eshantri** [comment]
![image](https://github.com/PecanProject/web/assets/48446729/e44d9642-110c-4d00-853d-ff3f87bc2775)
On chrome, the dev tools may not fully show how the website will look when on Phone, advisable to refresh your browser once to reflect changes. Hence closing this issue.
