### ISSUE TITLE
Packages out of Date

### ISSUE THREAD

**Issue by Sweetdevil144** [PecanProject/web#37]
I recently found 7 PRs over my for of `web` of DependableBots as shown in image below. I think a number of packages are out of date. Is there a way to automate the process to keep them up to date?
A number of packages offer a feature in `package.json` such as `package@latest` take Vite for example. But many don't.
Any approach or Suggestions ? 

<img width="1276" alt="Screenshot 2024-01-21 at 12 20 00 PM" src="https://github.com/PecanProject/web/assets/117591942/238a03ea-bfd3-4d44-bdf1-c5ccdc2aac09">

**Comment by Sweetdevil144** [comment]
@RohanSasne check this out : 
<img width="1440" alt="Screenshot 2024-01-21 at 3 58 34 PM" src="https://github.com/PecanProject/web/assets/117591942/5b2f0c7e-eec4-4029-9a05-3c4714a7c110">

**Comment by Sweetdevil144** [comment]
Any Updates @GandalfGwaihir

**Comment by Sweetdevil144** [comment]
@GandalfGwaihir below is the following instruction for configuring dependabot : 
> People with write permissions to a repository can enable or disable Dependabot version updates for the repository.

**Comment by robkooper** [comment]
this is now enabled, lets see what happens.

**Comment by Sweetdevil144** [comment]
Thanks @robkooper . I guess the issue is fixed now. So, we can close this issue for now. I will reopen this issue if I face any issues related to `dependabot`

**Comment by robkooper** [comment]
I'd like to keep it open until we get the first PR by dependabot.

**Comment by dlebauer** [comment]
closing this since code has been migrated github.com/pecanproject/pecanproject.github.io
